name: 'Setup Environment'
description: 'Install required dependencies and create initial directory structure'

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc tree

    - name: Create directory structure
      shell: bash
      run: |
        mkdir -p markdown-output
        find . -type d ! -path '*/\.*' ! -path './markdown-output*' -exec mkdir -p "markdown-output/{}" \;
