name: Convert and Deploy to Markdown

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

jobs:
  convert-and-deploy:
    name: Convert to Markdown and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Convert Files
        uses: ./.github/actions/convert-files

      - name: Generate Documentation
        uses: ./.github/actions/generate-docs

      - name: Deploy to S3
        uses: ./.github/actions/deploy-s3
        with:
          source-dir: markdown-output
          s3-bucket: ai-bedrock-service
          s3-prefix: orbitt-markdown
